package realtime

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/go-playground/validator/v10"
)

// definitions of message types the websocket handles
type MessageType string

const (
	//client->server, these need to be reacted to in client.ReadPump
	TypeDMSend MessageType = "direct_message_send"

	//server->client, these are generated by server and sent to client
	TypeInitialPresence MessageType = "initial_presence"
	TypePresenceUpdate  MessageType = "presence_update"
	TypeDMRecv          MessageType = "direct_message_recv"

// TypeError           MessageType = "error"
)

// message struct: a type, and then payload, which is any struct
type WebsocketMessage struct {
	Type    MessageType     `json:"type"`
	Payload json.RawMessage `json:"payload,omitempty"`
}

type InitialPresencePayload struct {
	OnlineUsers []string `json:"online_users"`
}

type PresenceUpdatePayload struct {
	Username     string `json:"username"`
	OnlineStatus bool   `json:"online_status"`
}

type DMSendPayload struct {
	Username string `json:"username" validate:"required,min=3,max=50"`
	Message  string `json:"message" validate:"required,min=1,max=2000"`
}

type DMRecvPayload struct {
	MessageID int64     `json:"message_id"`
	Sender    string    `json:"sender"`
	Message   string    `json:"message"`
	CreatedAt time.Time `json:"created_at"`
}

// generic websocket struct: who it's going to, and Data
type UserMessage struct {
	UserID int64
	Data   []byte
}

var validate = validator.New()

func UnmarshalAndValidate[T any](raw json.RawMessage) (T, error) {
	var target T
	if err := json.Unmarshal(raw, &target); err != nil {
		return target, fmt.Errorf("malformed JSON payload: %w", err)
	}

	if err := validate.Struct(target); err != nil {
		return target, fmt.Errorf("validation error: %w", err)
	}

	return target, nil
}

// helper to encode a message as a WebsocketMessage struct
func EncodeMessage(msgType MessageType, payload any) ([]byte, error) {
	payloadBytes, err := json.Marshal(payload)
	if err != nil {
		return nil, err
	}
	return json.Marshal(WebsocketMessage{
		Type:    msgType,
		Payload: payloadBytes,
	})
}
