package realtime

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/go-playground/validator/v10"
)

// definitions of message types the websocket handles
type MessageType string

const (
	//client->server, these need to be reacted to in client.ReadPump
	TypeDMSend         MessageType = "direct_message_send"
	TypeInviteSend     MessageType = "match_invite_send"
	TypeInviteResponse MessageType = "match_invite_response" //response to an incoming invite. if response is `rejected`, also goes server->client
	TypeInviteCancel   MessageType = "match_invite_cancel"   //cancelling an outgoing invite. also goes server->client

	//server->client, these are generated by server and sent to client
	TypeInitialPresence MessageType = "initial_presence"
	TypePresenceUpdate  MessageType = "presence_update"
	TypeDMRecv          MessageType = "direct_message_recv"
	TypeInviteRecv      MessageType = "match_invite_recv"
	TypeMatchStarted    MessageType = "match_started"

// TypeError           MessageType = "error"
)

// generic websocket struct: who it's going to, and Data
type UserMessage struct {
	UserID int64
	Data   []byte
}

// message struct: a type, and then payload, which is any struct encoded as json
type WebsocketMessage struct {
	Type    MessageType     `json:"type"`
	Payload json.RawMessage `json:"payload,omitempty"`
}

// Presence update payloads
type InitialPresencePayload struct {
	OnlineUsers []string `json:"online_users"`
}
type PresenceUpdatePayload struct {
	Username     string `json:"username"`
	OnlineStatus bool   `json:"online_status"`
}

// A unified payload used by all the direct_message_* types.
type DMPayload struct {
	ID        int64      `json:"id,omitempty"`
	Username  string     `json:"username" validate:"required,min=3,max=50"`             //which user Username is referencing depends on the message type: for _send, it's the target; for _recv, it's the sender
	Content   string     `json:"content,omitempty" validate:"omitempty,min=1,max=2000"` //omitempty to allow using this generic struct to send acknowledgment messsage as well, both send and recv should have content
	CreatedAt *time.Time `json:"created_at,omitempty"`
}

// A unified payload used by all match_invite_* message types
type MatchInvitePayload struct {
	Username string `json:"username" validate:"required,min=3,max=50"`
	Status   string `json:"status,omitempty"` // "pending", "accepted", "declined", "canceled"
}

var validate = validator.New()

func UnmarshalAndValidate[T any](raw json.RawMessage) (T, error) {
	var target T
	if err := json.Unmarshal(raw, &target); err != nil {
		return target, fmt.Errorf("malformed JSON payload: %w", err)
	}

	if err := validate.Struct(target); err != nil {
		return target, fmt.Errorf("validation error: %w", err)
	}

	return target, nil
}

// helper to encode a message as a WebsocketMessage struct
func EncodeMessage(msgType MessageType, payload any) ([]byte, error) {
	payloadBytes, err := json.Marshal(payload)
	if err != nil {
		return nil, err
	}
	return json.Marshal(WebsocketMessage{
		Type:    msgType,
		Payload: payloadBytes,
	})
}
